# Generated by Django 4.2 on 2023-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="city",),
        migrations.RemoveField(model_name="userprofile", name="country",),
        migrations.RemoveField(model_name="userprofile", name="email",),
        migrations.RemoveField(model_name="userprofile", name="full_name",),
        migrations.RemoveField(model_name="userprofile", name="state",),
        migrations.RemoveField(model_name="userprofile", name="username",),
        migrations.RemoveField(model_name="userprofile", name="zip",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
